In [2]:
from collections import defaultdict
city_list = [('TX','Austin'), ('TX','Houston'), ('NY','Albany'), ('NY', 'Syracuse'), ('NY', 'Buffalo'), ('NY', 'Rochester'), ('TX', 'Dallas'), ('CA','Sacramento'), ('CA', 'Palo Alto'), ('GA', 'Atlanta')]
cities_by_state = defaultdict(list)

In [3]:
for state, city in city_list:
    cities_by_state[state].append(city)

In [4]:
cities_by_state

defaultdict(list,
            {'CA': ['Sacramento', 'Palo Alto'],
             'GA': ['Atlanta'],
             'NY': ['Albany', 'Syracuse', 'Buffalo', 'Rochester'],
             'TX': ['Austin', 'Houston', 'Dallas']})

In [5]:
for state, cities in cities_by_state.items():
    print(state+' '+','.join(cities))

TX Austin,Houston,Dallas
NY Albany,Syracuse,Buffalo,Rochester
CA Sacramento,Palo Alto
GA Atlanta


In [10]:
a = [(1,4),(2,5),(3,6)]
b = zip(*a)
print(b)
print(a)

[(1, 4), (2, 5), (3, 6)]


In [7]:
a = [1,2,3]
b = [4,5,6]
zip(a,b)

## 蒙特卡洛



In [11]:
action = [0,1]
a = action.sample()


AttributeError: 'list' object has no attribute 'sample'

In [18]:

V = {(4, 7, False): -0.38775510204081631, (18, 6, False): -0.58434296365330851, (13, 2, False): -0.43409090909090908}
V[(4, 7, False)]

-0.3877551020408163

In [29]:
import time  
import sys  
for i in range(5):  
    print (i)
    sys.stdout.flush()  
#     time.sleep(1)  

在Linux系统下，必须加入sys.stdout.flush()才能一秒输一个数字

在Windows系统下，加不加sys.stdout.flush()都能一秒输出一个数字

0
1
2
3
4


In [30]:
a = [((8, 10, False), 1, 0), ((17, 10, False), 1, 0), ((19, 10, False), 0, -1.0)]
zip(*a) = [((8, 10, False),(17, 10, False) ,(19, 10, False)),(1,1,0),(0,0,-1.0)]
= [states,actions,rewards]

In [34]:
import numpy as np

discounts = np.array([0.9**i for i in range(10)])
print(discounts)
discounts[:-5]

[1.         0.9        0.81       0.729      0.6561     0.59049
 0.531441   0.4782969  0.43046721 0.38742049]


array([1.    , 0.9   , 0.81  , 0.729 , 0.6561])

In [77]:
return2 = defaultdict(list)

states = ((14, 2, False), (16, 2, False), (17, 2, False), (16, 2, False), (21, 2, False))
return2[(14, 2, False)].append(11)
return2[(14, 2, False)].append(21)
print(return2)
V = {k:np.mean(v) for  k,v in return2.items()}
print(V)


 

SyntaxError: invalid syntax (<ipython-input-77-c2eea01f1a48>, line 7)

In [65]:
import numpy as np
from collections import defaultdict
gamma = 0.9
returns = defaultdict(list)
episode = [((14, 2, False), 1, 0), ((16, 2, False), 1, 0), ((17, 2, False), 1, 0),((16, 2, False), 1, 0), ((21, 2, False), 0, 1.0)]
states, actions, rewards = zip(*episode)
print(states,actions,rewards)
print("-----")
discounts = np.array([gamma**i for i in range(len(rewards)+1)])
        # calculate and store the return for each visit in the episode
for i, state in enumerate(states):
    returns[state].append(sum(rewards[i:]*discounts[:-(1+i)]))
    
 
    
print(discounts)   
print("------")
print(returns.items())
V = {k: np.mean(v) for k, v in returns.items()}
print("-----")
print(V)

returns

((14, 2, False), (16, 2, False), (17, 2, False), (16, 2, False), (21, 2, False)) (1, 1, 1, 1, 0) (0, 0, 0, 0, 1.0)
-----
[1.      0.9     0.81    0.729   0.6561  0.59049]
------
dict_items([((14, 2, False), [0.6561]), ((16, 2, False), [0.7290000000000001, 0.9]), ((17, 2, False), [0.81]), ((21, 2, False), [1.0])])
-----
{(14, 2, False): 0.6561, (16, 2, False): 0.8145, (17, 2, False): 0.81, (21, 2, False): 1.0}


defaultdict(list,
            {(14, 2, False): [0.6561],
             (16, 2, False): [0.7290000000000001, 0.9],
             (17, 2, False): [0.81],
             (21, 2, False): [1.0]})

In [102]:
import numpy as np
a=np.array([i for i in range(10)])
print(a[2:])
print(a[:])
a[:]

[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
import gym
env = gym.make('Blackjack-v0')
# initialize empty dictionaries of arrays
returns_sum = defaultdict(lambda: np.zeros(env.action_space.n))
N = defaultdict(lambda: np.zeros(env.action_space.n))
Q = defaultdict(lambda: np.zeros(env.action_space.n))
# loop over episodes
 
episode = [((14, 2, False), 1, 0), ((16, 2, False), 1, 0), ((17, 2, False), 1, 0),((16, 2, False), 1, 0), ((21, 2, False), 0, 1.0)]
# obtain the states, actions, and rewards
states, actions, rewards = zip(*episode)
# prepare for discounting
discounts = np.array([gamma**i for i in range(len(rewards)+1)])
# update the sum of the returns, number of visits, and action-value 
# function estimates for each state-action pair in the episode
for i, state in enumerate(states):
    returns_sum[state][actions[i]] += sum(rewards[i:]*discounts[:-(1+i)])
    N[state][actions[i]] += 1.0
    Q[state][actions[i]] = returns_sum[state][actions[i]] / N[state][actions[i]]
Q

ModuleNotFoundError: No module named 'gym'

In [96]:

Q = defaultdict(lambda: np.zeros(2))
 
Q

defaultdict(<function __main__.<lambda>>, {})

In [111]:
action = np.random.choice(np.arange(2), p=0.8)
print(action)

TypeError: object of type 'float' has no len()

In [117]:
M = defaultdict(lambda: np.zeros(2))
M[0][0]

0.0

In [ ]:
def generate_episode_from_limit_stochastic(bj_env):
    episode = []
    state = bj_env.reset()
    while True:
        probs = [0.8, 0.2] if state[0] > 18 else [0.2, 0.8]
        action = np.random.choice(np.arange(2), p=probs)
        next_state, reward, done, info = bj_env.step(action)
        episode.append((state, action, reward))
        state = next_state
        if done:
            break
    return episode

In [ ]:
def mc_prediction_q(env, num_episodes, generate_episode, gamma=1.0):
    # initialize empty dictionaries of arrays
    returns_sum = defaultdict(lambda: np.zeros(env.action_space.n))
    N = defaultdict(lambda: np.zeros(env.action_space.n))
    Q = defaultdict(lambda: np.zeros(env.action_space.n))
    # loop over episodes
    for i_episode in range(1, num_episodes+1):
        # monitor progress
        if i_episode % 1000 == 0:
            print("\rEpisode {}/{}.".format(i_episode, num_episodes), end="")
            sys.stdout.flush()
        
        ## TODO: complete the function
        episode = generate_episode(env)
        states,actions,rewards = zip(*episode)
        
        discounts = np.array([gamma**i for i in range(len(rewards))])
        for i,state in enumerate(states):\
            # ?? actions[i]中i的含义
            returns_sum[state][actions[i]] += sum(rewards[i:]*discounts[:(len(states)-i)])
            N[state][actions[i]] += 1.0
            Q[state][actions[i]] = returns_sum[state][actions[i]] / N[state][actions[i]]

    return Q

In [124]:
np.ones(4)/4

array([0.25, 0.25, 0.25, 0.25])

In [123]:
np.random.randint(2)

1

In [125]:
Q=([((14, 2, False), array([ 0.    ,  0.6561])), ((16, 2, False), array([ 0.    ,  0.8145])), ((17, 2, False), array([ 0.  ,  0.81])), ((21, 2, False), array([ 1.,  0.]))])

NameError: name 'array' is not defined

In [128]:
probs = [0.5, 0.5] 
action = np.random.choice(np.arange(2), p=probs)
action

0

In [129]:
np.random.choice(10,3)

array([9, 0, 9])

In [134]:
a = np.ones(4)
a[:1111111]

array([1., 1., 1., 1.])

In [135]:
 Q = defaultdict(lambda: np.zeros(5))
print(Q.items())

dict_items([])


In [150]:
import numpy as np

# This is the sequence (corresponding to successively sampled returns). 
# Feel free to change it!
x = np.hstack((np.ones(10), 10*np.ones(10)))
print(x)
# These are the different step sizes alpha that we will test.  
# Feel free to change it!
alpha_values = np.arange(0.01,.31,.01)

#########################################################
# Please do not change any of the code below this line. #
#########################################################

def running_mean(x):
    mu = 0
    mean_values = []
    for k in np.arange(0, len(x)):
        mu = mu + (1.0/(k+1))*(x[k] - mu)
        mean_values.append(mu)
    return mean_values
    
def forgetful_mean(x, alpha):
    mu = 0
    mean_values = []
    for k in np.arange(0, len(x)):
        mu = mu + alpha*(x[k] - mu)
        mean_values.append(mu)
    return mean_values

def print_results():
    """
    prints the mean of the sequence "x" (as calculated by the
    running_mean function), along with analogous results for each value of alpha 
    in "alpha_values" (as calculated by the forgetful_mean function).
    """
    print('The running_mean function returns:', running_mean(x)[-1])
    print('The forgetful_mean function returns:')
    for alpha in alpha_values:
        print(np.round(forgetful_mean(x, alpha)[-1],4), \
        '(alpha={})'.format(np.round(alpha,2)))
print_results()

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10.]
The running_mean function returns: 5.5
The forgetful_mean function returns:
<class 'list'>
1.0427 (alpha=0.01)
<class 'list'>
1.9787 (alpha=0.02)
<class 'list'>
2.8194 (alpha=0.03)
<class 'list'>
3.5745 (alpha=0.04)
<class 'list'>
4.2529 (alpha=0.05)
<class 'list'>
4.8624 (alpha=0.06)
<class 'list'>
5.4099 (alpha=0.07)
<class 'list'>
5.9018 (alpha=0.08)
<class 'list'>
6.3436 (alpha=0.09)
<class 'list'>
6.7403 (alpha=0.1)
<class 'list'>
7.0964 (alpha=0.11)
<class 'list'>
7.4159 (alpha=0.12)
<class 'list'>
7.7025 (alpha=0.13)
<class 'list'>
7.9593 (alpha=0.14)
<class 'list'>
8.1894 (alpha=0.15)
<class 'list'>
8.3953 (alpha=0.16)
<class 'list'>
8.5795 (alpha=0.17)
<class 'list'>
8.7441 (alpha=0.18)
<class 'list'>
8.891 (alpha=0.19)
<class 'list'>
9.0221 (alpha=0.2)
<class 'list'>
9.1389 (alpha=0.21)
<class 'list'>
9.2428 (alpha=0.22)
<class 'list'>
9.3352 (alpha=0.23)
<class 'list'>
9.4173 (alpha=0.24)
<cla

In [157]:
a = ([4.1234,5.12344])
 
np.round(a[-1],4)
 

5.1234

In [171]:
import numpy as np
Q = defaultdict(lambda: np.zeros(env.action_space.n))

Q = dict([((12,13,11), np.array([0,0.9])),((1,3,21), np.array([1,8])),((121,113,111), np.array([2,0.4]))])
print(Q.items())
policy = dict((k,np.argmax(v)) for k,v in Q.items())
policy

dict_items([((12, 13, 11), array([0. , 0.9])), ((1, 3, 21), array([1, 8])), ((121, 113, 111), array([2. , 0.4]))])


{(1, 3, 21): 1, (12, 13, 11): 1, (121, 113, 111): 0}

# TD学习


In [2]:
import numpy as np
a = np.arange(48)
b = a.reshape(4,12)
nS = np.prod(b)
nS

0

In [193]:
np.prod(([4,4],[4,12]),axis = 1)

array([16, 48])

In [34]:
policy = np.hstack([np.ones(11), 2, 0, np.zeros(10), 2, 0, np.zeros(10), 2, 0, -1*np.ones(11)])
print(policy.reshape(4,12))


[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  2.]
 [ 0. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]


# 项目


###  二维字典更细

In [50]:
valid_actions = ['u', 'r', 'd', 'l']
Qtable = {1: {'l': 0}, 2: {'d': 2.0, 'l': 13.0, 'r': 221.0, 'u': 5.0}}
state = 2
 

policy = np.ones(4) / 4

if state not in Qtable:
#     Qtable.setdefault(state, {a: 0.0 for a in valid_actions})
    Qtable.update({state:{a: 0.0 for a in valid_actions}})

# print(max(Qtable[state]))
# print(max(Qtable[state], key = Qtable[state].get))
np.max(Qtable[2])
# dict= {'d': 2.0, 'l': 13.0, 'r': 221.0, 'u': 5.0}
# max(dict,key=dict.get)
np.dot(Qtable[2], policy)

TypeError: unsupported operand type(s) for *: 'dict' and 'float'

In [14]:
import random
import numpy as np
from collections import defaultdict

# if random.random() < self.epsilon:
#                 return True
#             else:              
#                 return False
random.random() < 0.1       

False

In [2]:
for i in (a,b):
    print(i)

NameError: name 'a' is not defined